genome: "/mnt/grid/meyer/hpc/home/data/common/public/annotations/genome/mouse/GRCm38"
refflat: "/sonas-hs/meyer/hpc/home/hmeyer/data/common/public/annotations/genome/mouse/GRCm38/mouse.GRCm38.refFlat"
