genomehuman: "/sonas-hs/meyer/hpc/home/hmeyer/data/common/public/annotations/genome/human/GRCh38"
refflat: "/sonas-hs/meyer/hpc/home/hmeyer/data/common/public/annotations/genome/human/GRCh38/human.GRCh38.refFlat"
multiplexed:
  mTEC-multiplexed: "--multiplexed \ "
  pt221-hi: ""
  pt221-lo: ""
  pt226-hi: ""
  pt226-lo: ""
spikeins:
  - "THR"
  - "LYS"
  - "PHE"
