genomehuman: "/sonas-hs/meyer/hpc/home/hmeyer/data/common/public/annotations/genome/human/GRCh37"
genomemouse: "/sonas-hs/meyer/hpc/home/hmeyer/data/common/public/annotations/genome/mouse"
refflat: "/sonas-hs/meyer/hpc/home/hmeyer/data/common/public/annotations/genome/human/GRCh37/human.GRCh37.p13.refFlat"
multiplexed:
  mTEC-multiplexed: "--multiplexed \ "
  pt221-hi: ""
  pt221-lo: ""
  pt226-hi: ""
  pt226-lo: ""
spikeins:
  - "THR"
  - "LYS"
  - "PHE"
