samples:
    - 'pt87-hi'
    - 'pt87-lo'
    - 'pt212-hi'
    - 'pt212-lo'
    - 'pt214-hi'
    - 'pt214-lo'
    - 'pt221-hi'
    - 'pt221-lo'
    - 'pt226-hi'
    - 'pt226-lo'

directory: '/mnt/grid/meyer/hpc/home/data/hmeyer/data/tss/human/5Pseq'

